[package]
name = "pkgutils"
version = "0.1.1"
build = "build.rs"

[lib]
name = "pkgutils"
path = "src/lib.rs"

[[bin]]
name = "pkg"
path = "src/bin/pkg.rs"

[dependencies]
bidir-map = "0.6.0"
clap = {version = "2.25", default-features = false}
libflate = "0.1.4"
liner = "0.1"
ordermap = "0.2.11"
pbr = { version = "1.0", git = "https://github.com/ids1024/pb", branch = "duration" }
petgraph = "0.4.5"
reqwest = { git = "https://github.com/redox-os/reqwest" }
serde = "1.0"
serde_derive = "1.0"
tar = { git = "https://github.com/redox-os/tar-rs" }
toml = "0.4"
version-compare = "0.0.4"

[dependencies.octavo]
git = "https://github.com/libOctavo/octavo.git"
default-features = false
features = ["digest"]
